name: orisha-recommendation-model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.15
  - numpy=1.26.4
  - scipy=1.17.1
  - joblib=1.5.3
  - pandas=3.0.2
  - scikit-learn=1.3.1
  - pip
  - nodejs=25.8.2
