name: salesagent
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - tensorflow
  - jupyterlab
  - pip
  - pip:
      - scikit-surprise
      - onnx
      - onnxruntime
      - tf2onnx